<script lang="ts">
    import type { DashboardGenerationState } from "$lib/types/dashboard";

    interface Props {
        state?: DashboardGenerationState;
        sourceReason?: string;
        class?: string;
    }

    let { state, sourceReason = "", class: className = "" }: Props = $props();

    const details = $derived(getDetails(state));

    function getDetails(value?: DashboardGenerationState) {
        switch (value) {
            case "generated":
                return {
                    label: "Generated",
                    title: "Generated by dashboard recipe",
                    classes:
                        "bg-m3-secondary-container text-m3-on-secondary-container",
                };
            case "user_modified":
                return {
                    label: "Edited",
                    title: "Generated card changed by user",
                    classes:
                        "bg-m3-tertiary-container text-m3-on-tertiary-container",
                };
            case "pinned":
                return {
                    label: "Pinned",
                    title: "Protected from future regeneration",
                    classes:
                        "bg-m3-primary-container text-m3-on-primary-container",
                };
            default:
                return null;
        }
    }
</script>

{#if details && state}
    <span
        class={`inline-flex h-6 max-w-full items-center rounded-m3-full px-2.5 text-m3-label-small font-medium shadow-m3-elevation-1 ${details.classes} ${className}`}
        data-generation-state={state}
        title={sourceReason ? `${details.title}: ${sourceReason}` : details.title}
    >
        {details.label}
    </span>
{/if}
